Homework #5: Multithreading
Android-Academy-Global/fundamentals-2020-homework pull request #8
Opened 2021-01-04 21:09 UTC by emartynov

## Description
Use JSON data instead of hardcoded one.

## Changes
* Add JSON data
* Add parsing on IO thread
* Modify UI to work with data
* Add coin library to load images from internet
* Remove unused resources

## Screenshots
<img width="380" alt="Screenshot 2021-01-04 at 22 04 52" src="https://user-images.githubusercontent.com/295424/103579835-5708db00-4ed9-11eb-9f2a-e0332a39523d.png">
<img width="382" alt="Screenshot 2021-01-04 at 22 04 35" src="https://user-images.githubusercontent.com/295424/103579861-68ea7e00-4ed9-11eb-8633-af00c3aa2d8d.png">

2021-01-06 09:10 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +
Для меня лично смотрится файл громоздко. Я бы разделили на модельки и отдельно загрузку и парсинг. Вынес бы в классы все. Может кто тестировать еще захочет :)

2021-01-06 09:11 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +                genresMap[it] ?: throw IllegalArgumentException("Genre not found")
Может сразу extension написать orThrow? Как например на orAssert.

2021-01-06 09:12 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +                genresMap[it] ?: throw IllegalArgumentException("Genre not found")
Я бы не приучал использовать it.

2021-01-06 09:12 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    val actorsMap = actors.associateBy { it.id }
Можно использовать референс функцию: GenreData::id

2021-01-06 09:25 UTC, PShchahelski requested changes

2021-01-06 09:25 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    val actorsMap = loadActors(context)
Я обычно код читаю сверху вниз и жду, что все функции, которые будут вызываться в теле текущей функции, окажутся снизу. Ты не так делаешь?

2021-01-06 09:25 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    val genresMap = loadGenres(context)
А мы не хотим бест практики? Я бы убрал контекст за пакет и класс platform.

2021-01-06 09:25 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    data: String,
А что такое data? из название аргумента непонятно :(

2021-01-06 09:25 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    val genresMap = loadGenres(context)
Я думаю, что можно было даже без ассетов обойтись, а просто стрингу json положить в store класс и в repository его распарсить и считать. Тогда бы и контекст не понадобился бы

2021-01-06 09:25 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/moviedetails/MovieDetailsFragment.kt
> +            movieData.genres.joinToString { it.name }
А мы не должны все это дело формировать во ViewModel и уже оттуда получать просто готовый стейт вью? Чтобы сразу приучать к тестированию.

2021-01-06 09:25 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +        coroutinesScope.launch {
Есть lifecycleScope уже в extensions. Можно его заюзать.

2021-01-06 09:25 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +    private var movies: List<MovieData>? = null
Точно ли нам надо хранить данные на ui уровне? может сделать, что данные храняться на уровне репозитория? Я понимаю, что подходы мы обсуждали позже. Может сразу чтоб красиво было с нашей стороны? По крайней мере потом переносить во вю модель будет проще.

2021-01-06 09:25 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/model/GenreData.kt
> +data class GenreData(val id: Int, val name: String)
Я не сторонник добавлять лишние слова например Data, которые могут запутать чуть :( Что ты думаешь?

2021-01-07 18:36 UTC, ermolnik commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +    private var movies: List<MovieData>? = null
у нас принято создавать пустые массивы listOf() вместо null, up to u

2021-01-07 20:08 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +
Идея было, что все приватное и только парсинг торчит наружу. Но в нетворке понадобятся модели, так что вынесу их в отдельные файлы.

2021-01-07 20:08 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +                genresMap[it] ?: throw IllegalArgumentException("Genre not found")
Сделал как упражнение.

2021-01-07 20:09 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +                genresMap[it] ?: throw IllegalArgumentException("Genre not found")
Ты не используешь `it` совсем?

2021-01-07 20:09 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +                genresMap[it] ?: throw IllegalArgumentException("Genre not found")
Поменял здесь.

2021-01-07 20:10 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    val actorsMap = actors.associateBy { it.id }
Сделал как упражнение

2021-01-07 20:10 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    val actorsMap = loadActors(context)
Я писал поэтапно, но сейчас перенес методы

2021-01-07 20:11 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    val genresMap = loadGenres(context)
Не понял про бест практики. Убрал контекст.

2021-01-07 20:13 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    data: String,
Переименовал. Не грусти.

2021-01-07 20:14 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/moviedetails/MovieDetailsFragment.kt
> +            movieData.genres.joinToString { it.name }
Не думал, что это скоуп этого задания.

2021-01-07 20:15 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +        coroutinesScope.launch {
Хотел показать как делать в общем и как отменять его. Могу переписать на lifecycle.

2021-01-07 20:17 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +    private var movies: List<MovieData>? = null
Тут тоже считал что делать все шаг за шагом по лекции. Кеширование репозитория будет тоже интересной задачей.

2021-01-07 20:18 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/model/GenreData.kt
> +data class GenreData(val id: Int, val name: String)
У меня изначально был`Genre`. Потом прилетела домашка по листам и там все было с Data. Я сделал для консистенции. Переименовал.

2021-01-07 20:19 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +    private var movies: List<MovieData>? = null
@ermolnik  пустой список не подходит, так как пустой может прийти с сервера и это валидное значение.

2021-01-07 20:25 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +    val genresMap = loadGenres(context)
Вообще не смог убрать контекст. Файлы довольно длинные, не охота из ложить в код.

2021-01-09 08:56 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonActor.kt
> +    val id: Int,
Не заметил сразу, сори. Я думаю лучше @SerialName добавлять сразу на все поля, чтобы потом они привыкли к такому и может даже явно рассказать почему и зачем так. Бо часто ведь обфускацию применяют в приложениях.

2021-01-09 08:56 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +
Да, понимаю, что нужно чтоб торчал только вот этот класс. Я к тому, чтобы не иметь одну статик функцию, а показать как ООП применяется. Что ответственности разделяются и т.д. У меня было бы  RemoteMoviesApi, MoviesMapping or MoviesParsing, GenreMaping, ActorMapping и т.д.

2021-01-09 08:56 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +private fun <T : Any> T?.orThrow(lambda: () -> Exception): T {
Nit: Я стараюсь, чтобы название лямбд всегда было понятно, что оно будет делать. Тут оно получается создает exceptions.

2021-01-09 08:56 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +        coroutinesScope.launch {
Ок, понимаю. На мой взгляд для этого у нас и была теоретическая часть. Тут уже мы хорошие практики начинаем показывать. Поэтому я бы заюзал.

2021-01-09 08:56 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/model/Movie.kt
>  ) : Serializable
Я бы не показывал про Serializable для обычного POJO класса если говорим про Android. Он должен быть Parcelable.
Я бы не делал ни Serializable ни Parcelable. Но тут сложности возникают как это лучше показать без этого. Тогда лучше оставить Parcelable тогда.

2021-01-09 08:56 UTC, PShchahelski commented on app/src/test/java/com/android/academy/fundamentals/homework/features/data/JsonLoadKtTest.kt
> +            Actor(
Классно, что тесты есть! Очень круто!
К тестам я отношусь как к нормальному коду, поэтому я бы выносил создание тестовых фикстур и потом переиспользовать, чтобы не плодить дубликаты создания.

2021-01-09 08:56 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/moviedetails/MovieDetailsFragment.kt
> +            movie.genres.joinToString { it.name }
Почитал ответ твой. Не знаю где лучше это сделать - в этом задании или нет :( Хочется конечно уже красоту навести ))

2021-01-09 14:58 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +
А в чем разница/преимущество классов перед функциями?

2021-01-09 15:11 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonActor.kt
> +    val id: Int,
Oбфускация тут не мешает, также как с моши. Адаптеры генерируются на этапе нормального кода и строковые константы остаются правильными.

2021-01-09 15:20 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/model/Movie.kt
>  ) : Serializable
Паша, это не мой класс. Видишь, в этом ПР эта строка не поменялась. 

У меня была идея, добавить многопоточность в текущий проект, и не было идеи переписать на свой вкус проект. 

Даже когда студенты сейчас сдают домашку и у них протягивается объект через бандл (parcelable или serailisable) я не пеналю их. Потому что у них еще нет репозиториев для кеширования, навигатора/роутера для передачи входа и выхода между логическими частями, они не думают про рестарт приложения и многое другое. Я даю свой комментарий какие есть в этом подходе проблемы.

2021-01-09 15:22 UTC, emartynov commented on app/src/test/java/com/android/academy/fundamentals/homework/features/data/JsonLoadKtTest.kt
> +            Actor(
Паша, а где ты увидел переиспользование в моих тестах?

2021-01-09 15:24 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +private fun <T : Any> T?.orThrow(lambda: () -> Exception): T {
Согласен, поменял

2021-01-09 15:29 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/moviedetails/MovieDetailsFragment.kt
> +            movie.genres.joinToString { it.name }
Идея у меня была, что каждая домашка делает что то лучше/другое соответственно с лекцией. След лекция была про модели.

Но даже с моделями, список будет показывать информацию 90% идентичную бизнес объекту. Я сильно задумался бы еще один класс для UI в котором разница будет что список жанров будет переведен в строку.

2021-01-09 15:33 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +        coroutinesScope.launch {
Переписал

2021-01-27 22:45 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/data/JsonLoad.kt
> +
Сделал репу но без маперов

2021-01-27 22:47 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +    private var movies: List<MovieData>? = null
Кеширование теперь в репе

2021-01-27 22:47 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/model/Movie.kt
>  ) : Serializable
Убрал сериалайзбл и гружу мови из репы

2021-01-31 08:29 UTC, PShchahelski approved these changes

2021-01-31 08:29 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/data/MovieRepository.kt
> +        return cachedMovies.find { it.id == movieId }!!
Я бы не делел !! и старался его не показывать народу. А лучше возвращать nullable и уже на юай обрабатывать. Эта обработка потом уйдет в viewmodel.

2021-01-31 08:31 UTC, PShchahelski commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +            withContext(Dispatchers.Main) {
А тут точно надо переводить на main? ведь сам скоуп ранится на main диспатчере. а репо ранится на своем диспатчере? или я путаюсь?

2021-01-31 08:50 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/features/movies/MoviesListFragment.kt
> +            withContext(Dispatchers.Main) {
Не нужно - убрал

2021-01-31 08:51 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/data/MovieRepository.kt
> +        return cachedMovies.find { it.id == movieId }!!
Доне

2021-01-31 08:51 UTC, merged

2021-02-01 08:56 UTC, emartynov commented on app/src/main/java/com/android/academy/fundamentals/homework/data/MovieRepository.kt
> +        return cachedMovies.find { it.id == movieId }!!
Сделал